
# configuration of Server Machine
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

#   script update apt and installs apache2
#   config.vm.provision "shell", path: "scripts/bootstrap.sh"

  config.vm.define "bamghougS" do |server|
	#   script that installs and runs K3s Server
	server.vm.provision "shell", path: "scripts/Server_script.sh"

	server.vm.network "private_network", ip: "192.168.56.110"

	server.vm.provider :virtualbox do |vb|
		vb.cpus = 2
		vb.memory = 2048
		vb.name = "bamghougS"
	end

  end	

  config.vm.define "bamghougSW" do |serverWorker|
	#   script that installs and runs K3s Agent
	serverWorker.vm.provision "shell", path: "scripts/ServerWorker_script.sh"
	
	serverWorker.vm.network "private_network", ip: "192.168.56.111"

	serverWorker.vm.provider :virtualbox do |vb|
		vb.cpus = 2
		vb.memory = 2048
		vb.name = "bamghougSW"
	end
  end

end
